apiVersion: apps/v1
kind: Deployment
metadata:
  name: circle-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circle-app
  template:
    metadata:
      labels:
        app: circle-app
    spec:
      containers:
        - name: circle-app
          image: circle-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: circle-app-secret


              