apiVersion: v1
kind: Secret
metadata:
  name: circle-app-secret
type: Opaque
stringData:
  JWT_SECRET: "super-secret-key"
  APP_BASE_URL: ""
  MAGIC_TOKEN_TTL_MIN: "10"

  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: ""
  SMTP_PASS: ""
  SMTP_FROM: ""